[package]
name = "solar_sailors"
version = "0.1.0"
authors = ["Oliver Scherer <github@oli-obk.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex2d = {version = "1.1.0", default-features = false}
macroquad = {version = "0.3", default-features = false}
orbital = {path = "orbital", version = "0.1"}
quad-storage = "0.1.2"
