# in .github/workflows/continuous_deployment.yml
name: Continuous deployment
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: jetli/trunk-action@v0.1.0
      - uses: jetli/wasm-bindgen-action@v0.1.0

      - uses: actions/checkout@v2

      - run: rustup target add wasm32-unknown-unknown
      - run: trunk build --release
      - run: cp target/wasm32-unknown-unknown/release/solar_sailors.wasm dist/solar_sailors.wasm

      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
