name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch dependencies
      run: sudo apt update
    - name: Install dependencies
      run: sudo apt -yq --no-install-suggests --no-install-recommends install libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
