# in .github/workflows/continuous_deployment.yml
name: Continuous deployment for android
on:
  workflow_run:
    branches: [main]
    workflows: [Continuous deployment]
    types: [completed]

jobs:
  release:
    runs-on: notfl3/cargo-apk
    steps:
      - uses: jetli/trunk-action@v0.1.0
      - uses: jetli/wasm-bindgen-action@v0.1.0

      - uses: actions/checkout@v2

      - run: rustup target add armv7-linux-androideabi
      
      - run: cargo quad-apk build --release
      - run: ls target/android-artifacts/release/apk/
      - run: cp target/android-artifacts/release/apk/solar_sailors.apk dist/solar_sailors.apk

      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
