# in .github/workflows/continuous_deployment.yml
name: Continuous deployment for android
on:
  workflow_run:
    branches: [main]
    workflows: [Continuous deployment]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker run --rm -v $(pwd)":/root/src" -w /root/src notfl3/cargo-apk sh android.sh
      - run: mkdir dist
      - run: cp target/android-artifacts/release/apk/solar_sailors.apk dist/solar_sailors.apk

      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true

      # deploy to itch
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: android
          ITCH_GAME: solar-sailors
          ITCH_USER: oli-obk
          PACKAGE: dist/solar_sailors.apk
